# -*- coding: utf-8 -*-
"""Wine_s5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pZgEVQfczfrsxr6VRiRPUNb3EyPL6VBx
"""

pip install streamlit

import joblib
import numpy as np
import streamlit as st

m = joblib.load('wine_type_pred.pkl')

st.set_page_config(page_title="Wine Type Classification", layout = 'centered')
st.title("🍷 Type classification app")
st.write("Predict whether the wine is 'Red' or 'White' using chemical properties")

fixed_acidity = st.number_input("Value of fixed Acidity",value=None)
volatile_acidity = st.number_input("Value of Volatile acidity",value=None)
citric_acid = st.number_input("Value of Citric Acid",value=None)
residual_sugar = st.number_input("Value of residual sugar",value=None)
chlorides = st.number_input("Value of Chlorides",value=None)
free_sulfur_dioxide = st.number_input("Value of Free sulfur dioxide",value=None)
total_sulfur_dioxide =st.number_input("Value of Total sulfur dioxide",value=None)
density =st.number_input("Value of Density",value=None)
pH = st.number_input("Value of pH",value=None)
sulphates =st.number_input("Value of Sulphates",value=None)
alcohol = st.number_input("Value of Alcohol",value=None)
quality = st.number_input("Value of Quality",value=None)

if st.button("Predict"):
  input_data = np.array([[fixed_acidity,
                          volatile_acidity,
                          citric_acid,
                          residual_sugar,
                          chlorides,
                          free_sulfur_dioxide,
                          total_sulfur_dioxide,
                          density,
                          pH,
                          sulphates,
                          alcohol,
                          quality]])
  prediction = m.predict(input_data)[0]
  if prediction == 0:
    st.error("Red Wine")
  else:
    st.success("White Wine")